name: Deploy Static Site Manually
permissions:
  contents: read
  pages: write
  id-token: write
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
env:
  NODE_VERSION: '20.x'
  DEFAULT_BRANCH: main
  NODE_CACHE: 'npm'
  GIT_USER: "github-actions-bot <support+actions@github.com>"
jobs:
  build:
    name: Build-and-Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ '20.x' ]
    steps:
      # Use node
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node.js Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: ${{ env.NODE_CACHE }}
      # Install dependencies
      - name: Install Dependencies
        run: npm ci
      # Build
      - name: Build Project
        run: npm run build
      # Upload built artifact to gh-pages
      - name: Upload artifact to GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./build"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
