name: CI-Workflow
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  NODE_VERSION: '20.x'
  DEFAULT_BRANCH: main
  NODE_CACHE: 'npm'
  GIT_USER: "github-actions-bot <support+actions@github.com>"
jobs:
  build:
    name: Build-and-Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ '20.x' ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node.js Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: ${{ env.NODE_CACHE }}
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: npm run build --if-present
      - name: Set up GitHub token and repository
        run: |
          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
          echo "GITHUB_REPOSITORY=${{ github.repository }}" >> $GITHUB_ENV
      - name: Deploy to GitHub Pages
        #uses: actions/setup-node@v3
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy -- -u ${{ env.GIT_USER }}
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
